version: "3.8"
services:
  frontend:
    container_name: netlify-deploy-notification
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    command: npm run start # Start the Next.js app in production mode

